version: '3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - db
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/var/www
    depends_on:
      - db
    working_dir: /var/www
    tty: true
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stoadb
      MYSQL_USER: stoa
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
